# Generated by Django 5.1.2 on 2024-10-26 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='user',
        ),
        migrations.AddField(
            model_name='idea',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='idea',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='idea',
            name='name',
            field=models.CharField(default='Unnamed Idea', max_length=100),
        ),
        migrations.AddField(
            model_name='idea',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='phone',
            field=models.CharField(default='1234567890', max_length=15),
        ),
        migrations.AddField(
            model_name='idea',
            name='sdg_goal',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='idea',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(default='NULL', max_length=500),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(default='Untitled Idea', max_length=200),
        ),
    ]
