# Generated by Django 5.1.2 on 2024-10-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborate', '0003_idea_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='idea',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='idea',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='idea',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='idea',
            name='sdg_goal',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
